from sys import path as syspath
syspath.insert(0, '/Games/CatsEmblem')

from Shared import Cat, Dialog, House, Position, Shop, ShopItem, Stats, itemDict
import thumbyGrayscale as thumby

def cat_sprite(): return thumby.Sprite(8, 8, (bytearray([0, 207, 15, 15, 192, 5, 241, 244, 6, 201, 15, 15, 192, 5, 241, 244, 7, 201, 14, 15, 192, 5, 241, 244, 1, 206, 15, 15, 192, 5, 241, 244])), 32, 16, key=1)
def enemy_sprite(): return thumby.Sprite(8, 8, (bytearray([3, 143, 2, 4, 129, 1, 228, 242, 3, 143, 2, 4, 145, 17, 196, 242, 7, 139, 2, 4, 129, 1, 228, 242]), bytearray([252, 112, 253, 251, 118, 246, 27, 13, 252, 112, 253, 251, 102, 230, 59, 13, 248, 116, 253, 251, 118, 246, 27, 13])), 32, 16, key=1)

_add_to_party = None
_update_bank = None
_can_give_item = None
_give_item = None
_get_cat_at_pos = None

def set_game_state_callbacks(add_to_party, update_bank, can_give_item, give_item, get_cat_at_pos):
	global _add_to_party, _update_bank, _can_give_item, _give_item, _get_cat_at_pos
	_add_to_party = add_to_party
	_update_bank = update_bank
	_can_give_item = can_give_item
	_give_item = give_item
	_get_cat_at_pos = get_cat_at_pos

# Use the callbacks in your code
def add_party_member(cat):
	if _add_to_party:
		_add_to_party(cat)

def modify_bank(amount):
	if _update_bank:
		_update_bank(amount)

def can_give_item(position: Position) -> bool:
	if _can_give_item:
		return _can_give_item(position)
	return False

def give_item(position: Position, item) -> bool:
	if _give_item:
		_give_item(position, item)

def get_cat_at_position(position: Position):
	if _get_cat_at_pos:
		return _get_cat_at_pos(position)
	return None

# --- UNITS ---
cat = Cat(
	cat_sprite(),
	Position(2, 4),
	'cat',
	False,
	False,
	Stats(attack=5, defense=3, max_hp=10, speed=8, luck=4, range=4),
	None,
	False,
	items=[itemDict['Stick'], itemDict['Tuna']],
)

tac = Cat(
	cat_sprite(),
	Position(5, 13),
	'tac',
	False,
	False,
	Stats(attack=4, defense=4, max_hp=8, speed=8, luck=4, range=5),
	None,
	False,
	items=[itemDict['Slngsht']]
)

mew = Cat(
	sprite=cat_sprite(),
	name='mew',
	position=Position(3,1),
	stats=Stats(attack=4, defense=4, max_hp=8, speed=8, luck=4, range=5),
	enemy=True,
	items=[itemDict['Slngsht']]
)

npc = Cat(
	sprite=cat_sprite(),
	name='npc',
	position=Position(0,0),
	stats=Stats(attack=0, defense=0, max_hp=1, speed=0, luck=0, range=0),
	enemy=False,
	items=[]
)

TILE_GRASS = 0
TILE_FOREST = 1
TILE_MOUNTAIN = 2
TILE_HOUSE = 3
EMPTY = 4
TILE_WATER = 5
TILE_COAST_X = 6
TILE_COAST_XFLIP = 7
TILE_COASTY = 8
TILE_COASTY_YFLIP = 9
TILE_BRIDGE = 10
TILE_CLIFFBTLBR = 11
TILE_CLIFF_B_TLBR_XFLIP = 12
TILE_CLIFF_B_TLBR_YFLIP = 13
TILE_CLIFF_B_TLBR_XYFLIP = 14
TILE_CLIFF_TTLBR = 15
TILE_CLIFF_TTLBR_XFLIP = 16
TILE_CLIFF_STRAIGHT = 17
TILE_STAIRS = 18
TILE_SHOP = 19
WALL_TOP = 20
WALL_SIDE = 21
TILE_CLIFF_TOP = 22
TILE_CLIFF_TOP_YFLIP = 23
TILE_CLIFF_RIGHT = 24
TILE_CLIFF_RIGHT_XFLIP = 25
TILE_COAST_CORNER_BR = 26
TILE_COAST_CORNER_BR_XFLIP = 27
TILE_COAST_CORNER_BR_YFLIP = 28
TILE_COAST_CORNER_BR_XYFLIP = 29
TILE_WATER_CLIFF = 30
TILE_WATER_CLIFF_YFLIP = 31
TILE_WATER_CLIFF_XFLIP = 32
TILE_WATER_CLIFF_XYFLIP = 33

tiles = {
	TILE_GRASS: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([0, 64, 0, 64, 4, 0, 4, 0])), "XFLIP": False, "YFLIP": False},
	TILE_FOREST: {"sprite": (bytearray([255, 255, 255, 255, 127, 255, 255, 255]), bytearray([0, 0, 96, 124, 255, 124, 96, 0])), "XFLIP": False, "YFLIP": False},
	TILE_MOUNTAIN: {"sprite": (bytearray([255, 255, 255, 255, 255, 252, 227, 31]), bytearray([192, 240, 252, 255, 255, 255, 252, 224])), "XFLIP": False, "YFLIP": False},
	TILE_HOUSE: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([8, 252, 142, 239, 239, 142, 252, 8])), "XFLIP": False, "YFLIP": False},
	TILE_WATER: {"sprite": (bytearray([0, 4, 2, 4, 64, 32, 64, 0, 0, 0, 4, 66, 36, 64, 0, 0]), bytearray([0, 4, 2, 4, 64, 32, 64, 0, 0, 0, 4, 66, 36, 64, 0, 0])), "XFLIP": False, "YFLIP": False},
	TILE_COAST_X: {"sprite": (bytearray([0, 64, 160, 0, 7, 136, 86, 239, 0, 4, 10, 0, 64, 161, 86, 239]), bytearray([0, 64, 160, 0, 7, 136, 16, 0, 0, 4, 10, 0, 64, 161, 16, 0])), "XFLIP": False, "YFLIP": False},
	TILE_COASTY: {"sprite": (bytearray([160, 208, 136, 16, 164, 194, 196, 160, 160, 196, 130, 68, 160, 208, 208, 160]), bytearray([32, 16, 8, 16, 36, 2, 4, 32, 32, 4, 2, 68, 32, 16, 16, 32])), "XFLIP": False, "YFLIP": False},
	TILE_BRIDGE: {"sprite": (bytearray([126, 126, 126, 126, 126, 126, 126, 126]), bytearray([193, 193, 193, 193, 193, 193, 193, 193])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_TOP: {"sprite": (bytearray([254, 254, 254, 254, 254, 254, 254, 254]), bytearray([1, 1, 1, 1, 1, 1, 1, 1])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_RIGHT: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 0]), bytearray([0, 0, 0, 0, 0, 0, 0, 255])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFFBTLBR: {"sprite": (bytearray([126, 253, 251, 247, 239, 223, 191, 127]), bytearray([255, 254, 252, 248, 240, 224, 192, 128])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_TTLBR: {"sprite": (bytearray([127, 191, 223, 239, 247, 251, 253, 254]), bytearray([128, 64, 32, 16, 72, 36, 66, 1])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_STRAIGHT: {"sprite": (bytearray([126, 126, 126, 126, 126, 126, 126, 126]), bytearray([255, 255, 255, 255, 255, 255, 255, 255])), "XFLIP": False, "YFLIP": False},
	TILE_COAST_CORNER_BR: {"sprite": (bytearray([160, 208, 160, 0, 164, 217, 194, 247, 136, 200, 128, 4, 130, 192, 194, 247]), bytearray([32, 16, 32, 0, 36, 25, 0, 0, 8, 8, 0, 4, 2, 0, 0, 0])),"XFLIP": False, "YFLIP": False },
	TILE_STAIRS: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([85, 85, 85, 85, 85, 85, 85, 85])), "XFLIP": False, "YFLIP": False},
	TILE_SHOP: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([254, 2, 5, 229, 229, 5, 2, 254])), "XFLIP": False, "YFLIP": False},
	WALL_TOP: {"sprite": (bytearray([127, 127, 127, 127, 127, 127, 127, 1]), bytearray([128, 254, 254, 254, 254, 254, 254, 254])), "XFLIP": False, "YFLIP": False},
	WALL_SIDE: {"sprite": (bytearray([17, 17, 68, 68, 17, 17, 68, 68]), bytearray([85, 17, 85, 68, 85, 17, 85, 68])), "XFLIP": False, "YFLIP": False},
	TILE_WATER_CLIFF: {"sprite": (bytearray([0, 1, 3, 7, 15, 31, 63, 127]), bytearray([1, 2, 4, 8, 16, 32, 64, 128])), "XFLIP": False, "YFLIP": False},
}
tiles.update({
	TILE_COAST_XFLIP: dict(tiles[TILE_COAST_X], XFLIP=True),
	TILE_COASTY_YFLIP: dict(tiles[TILE_COASTY], YFLIP=True),
	TILE_CLIFF_B_TLBR_XFLIP: dict(tiles[TILE_CLIFFBTLBR], XFLIP=True),
	TILE_CLIFF_B_TLBR_YFLIP: dict(tiles[TILE_CLIFFBTLBR], YFLIP=True),
	TILE_CLIFF_B_TLBR_XYFLIP: dict(tiles[TILE_CLIFFBTLBR], XFLIP=True, YFLIP=True),
	TILE_CLIFF_TTLBR_XFLIP: dict(tiles[TILE_CLIFF_TTLBR], XFLIP=True),
	TILE_COAST_CORNER_BR_XFLIP: dict(tiles[TILE_COAST_CORNER_BR], XFLIP=True),
	TILE_COAST_CORNER_BR_YFLIP: dict(tiles[TILE_COAST_CORNER_BR], YFLIP=True),
	TILE_COAST_CORNER_BR_XYFLIP: dict(tiles[TILE_COAST_CORNER_BR], XFLIP=True, YFLIP=True),
	TILE_WATER_CLIFF_YFLIP: dict(tiles[TILE_WATER_CLIFF], YFLIP=True),
	TILE_WATER_CLIFF_XFLIP: dict(tiles[TILE_WATER_CLIFF], XFLIP=True),
	TILE_WATER_CLIFF_XYFLIP: dict(tiles[TILE_WATER_CLIFF], XFLIP=True, YFLIP=True),
})

canWalkOn = {
	TILE_GRASS: True,
	TILE_FOREST: True,
	TILE_MOUNTAIN: False,
	TILE_HOUSE: True,
	EMPTY: True,
	TILE_WATER: False,
	TILE_COAST_X: False,
	TILE_COAST_XFLIP: False,
	TILE_COASTY: False,
	TILE_COASTY_YFLIP: False,
	TILE_BRIDGE: True,
	TILE_CLIFFBTLBR: False,
	TILE_CLIFF_B_TLBR_XFLIP: False,
	TILE_CLIFF_B_TLBR_YFLIP: False,
	TILE_CLIFF_B_TLBR_XYFLIP: False,
	TILE_CLIFF_TTLBR: False,
	TILE_CLIFF_TTLBR_XFLIP: False,
	TILE_CLIFF_STRAIGHT: False,
	TILE_STAIRS: True,
	TILE_SHOP: True,
	WALL_TOP: False,
	WALL_SIDE: False,
	TILE_CLIFF_TOP: True,
	TILE_CLIFF_TOP_YFLIP: True,
	TILE_CLIFF_RIGHT: True,
	TILE_CLIFF_RIGHT_XFLIP: True,
	TILE_COAST_CORNER_BR: False,
	TILE_COAST_CORNER_BR_XFLIP: False,
	TILE_COAST_CORNER_BR_YFLIP: False,
	TILE_COAST_CORNER_BR_XYFLIP: False,
}

tileEncumberence = {
	TILE_FOREST: 2,
}

tileEvation = {
	TILE_FOREST: 20,
	TILE_GRASS: 5,
	TILE_HOUSE: 10,
	TILE_SHOP: 10,
}

map1 = [
	[TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
	[TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER],
	[TILE_GRASS, TILE_HOUSE, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_COASTY, TILE_COASTY],
	[TILE_FOREST, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN],
	[WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
	[WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE],
	[TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, TILE_FOREST, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_HOUSE, TILE_SHOP, TILE_HOUSE, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN],
	[TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST],
	[TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST],
	[TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST]
]

map2 = [
	[TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST],
	[TILE_GRASS, EMPTY, TILE_HOUSE, EMPTY, TILE_HOUSE, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, TILE_FOREST, WALL_TOP],
	[EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, WALL_SIDE],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[WALL_SIDE, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, TILE_HOUSE, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, WALL_TOP],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_HOUSE, WALL_SIDE],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY]
]

map3 = [
	[EMPTY, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_FOREST, WALL_TOP, TILE_BRIDGE, WALL_TOP, TILE_FOREST],
	[TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XYFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COAST_CORNER_BR_YFLIP, WALL_SIDE, TILE_HOUSE, WALL_SIDE, EMPTY],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER, TILE_COAST_X, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY],
	[WALL_TOP, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_TOP, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT],
	[WALL_SIDE, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, WALL_SIDE, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, EMPTY, TILE_GRASS, TILE_HOUSE, TILE_GRASS, TILE_GRASS],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST],
	[EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, WALL_TOP, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_TOP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT],
	[TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_GRASS, TILE_GRASS, WALL_SIDE, EMPTY, EMPTY, EMPTY, EMPTY, WALL_SIDE, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY],
	[EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
]

map4 = [
    [TILE_HOUSE, TILE_HOUSE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
    [EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY],
    [EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XYFLIP],
    [EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_XFLIP],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER],
    [EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_COAST_XFLIP, TILE_WATER],
    [EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_WATER],
    [EMPTY, TILE_GRASS, EMPTY, TILE_SHOP, TILE_MOUNTAIN, EMPTY, EMPTY, TILE_COAST_XFLIP, TILE_WATER],
    [EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER],
    [EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XFLIP],
    [EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
    [TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_HOUSE, EMPTY],
    [EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS]
]

map5 = [
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_HOUSE, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, TILE_FOREST, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS],
	[TILE_WATER, TILE_WATER, TILE_BRIDGE, TILE_BRIDGE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_HOUSE, TILE_GRASS],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_FOREST, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_BRIDGE, TILE_BRIDGE, TILE_BRIDGE, TILE_BRIDGE, TILE_BRIDGE, EMPTY, TILE_FOREST, EMPTY, TILE_FOREST, TILE_FOREST, TILE_HOUSE, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
]

map6 = [
	[WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
	[WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, EMPTY, WALL_SIDE, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, WALL_SIDE, EMPTY, WALL_SIDE, WALL_SIDE, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, EMPTY, WALL_SIDE, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_SIDE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
	[WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP]
]

map7 = [
	[TILE_GRASS, TILE_FOREST, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, TILE_HOUSE, EMPTY, TILE_SHOP, EMPTY, TILE_FOREST, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, TILE_HOUSE, TILE_GRASS, TILE_MOUNTAIN, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_FOREST],
	[TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY],
	[TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, TILE_MOUNTAIN, EMPTY, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[EMPTY, TILE_FOREST, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY],
	[TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_HOUSE, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_MOUNTAIN]
]

map8 = [
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
	[TILE_WATER_CLIFF_YFLIP, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER],
	[TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_HOUSE, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_GRASS, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER],
	[TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_WATER, TILE_COAST_X, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_WATER],
	[TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_COAST_XFLIP],
	[TILE_CLIFF_B_TLBR_XYFLIP, WALL_SIDE, WALL_SIDE, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_SIDE, WALL_SIDE, TILE_CLIFF_B_TLBR_YFLIP, TILE_COAST_XFLIP, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_COAST_XFLIP],
	[TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_COAST_CORNER_BR_XYFLIP, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP],
	[TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER, TILE_COAST_X, WALL_TOP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_COAST_XFLIP],
	[TILE_COAST_X, TILE_GRASS, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, EMPTY, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_X, WALL_SIDE, WALL_TOP, WALL_TOP, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, TILE_COAST_XFLIP],
	[TILE_COAST_X, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, WALL_SIDE, WALL_SIDE, EMPTY, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, TILE_COAST_XFLIP],
	[TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_COAST_XFLIP, TILE_COAST_X, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_HOUSE, TILE_HOUSE, TILE_MOUNTAIN, TILE_COAST_XFLIP],
	[TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_BRIDGE, TILE_BRIDGE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_COAST_XFLIP],
	[TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_WATER],
	[TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER, TILE_WATER]
]

map9 = [
	[TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, WALL_TOP, WALL_TOP, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_TOP, WALL_TOP],
	[TILE_GRASS, TILE_HOUSE, TILE_HOUSE, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, WALL_SIDE, WALL_SIDE, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_SIDE, WALL_SIDE],
	[TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[WALL_SIDE, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_SIDE, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP],
	[TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT],
	[TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
	[TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST],
	[EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY],
	[TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY]
]

def get_stats_for_level(level: int):
	return Stats(
		attack=3 + level,
		defense=2 + level,
		max_hp=7 + level,
		speed=2 + level,
		luck=1 + level,
		range=3
	)

def generate_enemy(level: int, position: Position, ai='searchAndDestroy', name='enemy', weapon="Stick", classType='pupil'):
	enemySprite = enemy_sprite()
	return Cat(
		sprite=enemySprite,
		position=position,
		name=name,
		selected=False,
		exhausted=False,
		stats=get_stats_for_level(level),
		enemy=True,
		level=level,
		next_level_exp=level * 10,
		exp=0,
		aiType=ai,
		items=[itemDict[weapon]],
		classType=classType
	)

class Conversation:
	def __init__(
			self,
			dialogs: list[Dialog],
			nameOne: str='',
			nameTwo: str='',
			condition: callable=lambda: True
		):
		self.dialogs = dialogs
		self.nameOne = nameOne
		self.nameTwo = nameTwo
		self.condition = condition

class Level:
	def __init__(
			self,
			map: list[list[int]],
			enemies: list[Cat],
			number: int=1,
			seizePosition=Position(1, 1),
			startingPositions=[],
			shops: list[Shop]=[],
			houses: list[House]=[],
			conversations: list[Conversation]=[]
		):
		self.map = map
		self.enemies = enemies
		self.viewport = Position()
		self.selectorPosition = Position()
		self.number = number
		self.seizePosition = seizePosition
		self.startingPositions = startingPositions
		self.shops = shops
		self.houses: list[House] = houses
		self.conversations: list[Conversation] = conversations

# --- LEVELS ---
level1 = Level(
	map = map1, 
	enemies=[
		generate_enemy(1, Position(4, 4), name='bork'),
		generate_enemy(1, Position(6, 4), name='bark', weapon='Slngsht'),
		generate_enemy(1, Position(1, 2), ai='stand', name='sean', classType='warrior')
	], 
	number=1, 
	seizePosition=Position(1, 2),
	startingPositions=[Position(6,14), Position(8,14)],
	houses = [
		House(
			position = Position(6, 11),
			dialogs=[Dialog(
				lines=["save our","village,","take 50g"],
				left_cats=[get_cat_at_position(Position(6, 11))],
				right_cats=[npc],
				currentlyTalking='npc',
				lambda_after=lambda: modify_bank(50)
			)],
			postVisitDialog=[Dialog(
				lines=["Thats all","we got"],
				left_cats=[get_cat_at_position(Position(6, 11))],
				right_cats=[npc],
				currentlyTalking='npc'
			)]
		),
		House(
			position=Position(8, 11),
			dialogs=[Dialog(
				lines=["TAC","join me","tac"],
				left_cats=[cat],
				right_cats=[tac],
				currentlyTalking='cat',
				lambda_after=lambda: (tac.set_position(Position(8, 12)), add_party_member(tac))
			), Dialog(
				lines=["Just woke","up...","okay"],
				left_cats=[cat],
				right_cats=[tac],
				currentlyTalking='tac'
			)],
		),
	],
	shops = [
		Shop(
			Position(7, 11),
			inventory=[
				ShopItem(itemDict['Tuna'], 8),
				ShopItem(itemDict['Stick'], 10),
				ShopItem(itemDict['Slngsht'], 20)
			]
		)
	]
)

level2 = Level(
	map=map2,
	enemies=[
		generate_enemy(1, Position(9, 8), name='mut'),
		generate_enemy(2, Position(11, 9), name='mut'),
		generate_enemy(2, Position(2, 6), name='mut'),
		generate_enemy(2, Position(3, 13), name='mut'),
		generate_enemy(2, Position(4, 11), name='mut', weapon='Slngsht'),
		generate_enemy(3, Position(1, 12), ai='stand', name='guy', classType='warrior', )
	],
	number=2,
	seizePosition=Position(1, 12),
	startingPositions=[Position(10,1), Position(11,1), Position(10,2)],
	houses=[
		House(
			position=Position(2, 1),
			preVistedDialogs=[Dialog(
				lines=["Save us","and I'll", "owe you"],
				left_cats=[get_cat_at_position(Position(2, 1))],
				right_cats=[npc],
				currentlyTalking='npc'
			)],
			dialogs=[Dialog(
				lines=["Thank you" ,"take this."],
				left_cats=[get_cat_at_position(Position(2, 1))],
				right_cats=[npc],
				currentlyTalking='npc',
				lambda_after=lambda: give_item(Position(2,1), itemDict['MystPot'])
			)],
			visitCondition=lambda: (level2.enemies == [] and can_give_item(Position(2,1)))
		),
		House(
			position=Position(4, 1),
			dialogs=[
			Dialog(
				lines=["Trees,","grass,","and house"],
				left_cats=[get_cat_at_position(Position(4, 1))],
				right_cats=[npc],
				currentlyTalking='npc'
			),
			Dialog(
				lines=["Give", "Extra", "Avoid"],
				left_cats=[get_cat_at_position(Position(4, 1))],
				right_cats=[npc],
				currentlyTalking='npc'
			)]
		),
		House(
			position=Position(12, 13),
			dialogs=[
				Dialog(
					lines=["I hear","some","items..."],
					left_cats=[get_cat_at_position(Position(12, 13))],
					right_cats=[npc],
					currentlyTalking='npc'
				),
				Dialog(
					lines=["promote", "trained", "pupils"],
					left_cats=[get_cat_at_position(Position(12, 13))],
					right_cats=[npc],
					currentlyTalking='npc'
				)
			]
		)
	]
)

level3 = Level(
	map=map3,
	enemies=[
		generate_enemy(2, Position(14, 8), name='mut'),
		generate_enemy(2, Position(3, 9), name='mut'),
		generate_enemy(2, Position(7, 13), name='mut'),
		generate_enemy(2, Position(9, 4), name='mut'),
		generate_enemy(2, Position(19, 3), name='mut'),
		mew,
		generate_enemy(3, Position(17, 1), ai='stand', name='guard', classType='warrior')
	],
	number=3,
	startingPositions=[Position(11, 13), Position(12, 14)],
	seizePosition=Position(17, 1),
	houses=[
		House(
			position=Position(17, 8),
			preVistedDialogs=[Dialog(
				lines=["There is","a legendary","cat..."],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='npc'
			),
			Dialog(
				lines=["that","possesses", "the dna.."],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='cat'
			),
			Dialog(
				lines=["of all","species.", "Its name.." ],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='cat'
			),
			Dialog(
				lines=["is mew.", "cat must", "save him"],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='cat'
			)],
			visitCondition=lambda: get_cat_at_position(Position(17, 8)) is not None and get_cat_at_position(Position(17, 8)).name == 'mew' and can_give_item(Position(17,8)),
			dialogs=[
				Dialog(
					lines=["They","beileved","me huh..."],
					left_cats=[get_cat_at_position(Position(17, 8))],
					right_cats=[npc],
					currentlyTalking='npc',
				),
				Dialog(
					lines=["Take after","my steps","will ya"],
					left_cats=[get_cat_at_position(Position(17, 8))],
					right_cats=[npc],
					currentlyTalking='npc',
					lambda_after=lambda: (give_item(Position(17,8), itemDict['MstQll']))
				),
			],
			postVisitDialog=[Dialog(
				lines=["Don't die", "live"],
				left_cats=[get_cat_at_position(Position(17, 8))],	
				right_cats=[npc],
				currentlyTalking='npc'
			)]
		),
	],
	conversations=[
		Conversation(
			dialogs=[
				Dialog(
					lines=["Mew", 'why join', 'them'],
					left_cats=[mew],
					right_cats=[cat],
					currentlyTalking='cat'
				),
				Dialog(
					lines=["meow :("],
					left_cats=[cat],
					right_cats=[mew],
					currentlyTalking='mew',
					lambda_after=lambda: (
						level3.enemies.remove(mew),
						setattr(mew, 'enemy', False),
						add_party_member(mew)
					)
				)
			],
			nameOne='cat',
			nameTwo='mew',
			condition=lambda: mew in level3.enemies and get_cat_at_position(Position(17, 8)) is not None and get_cat_at_position(Position(17, 8)).name == 'cat'
		)
	]
)

level4 = Level(
	map=map4,
	enemies=[
		generate_enemy(2, Position(0, 4), name='mut'),
		generate_enemy(3, Position(2, 9), name='mut', weapon='LongBow', classType='sniper'),
		generate_enemy(2, Position(2, 11), name='mut'),
		generate_enemy(3, Position(3, 10), name='mut'),
		generate_enemy(4, Position(3, 9), name='arch', weapon='LghtngTm', classType='mech', ai='stand'),
	],
	number=4,
	seizePosition=Position(3, 9),
	startingPositions=[Position(7,1), Position(6,2), Position(8,2)],
	houses=[
		House(
			position=Position(0, 0),
			preVistedDialogs=[Dialog(
				lines=["muggle,","freaking", "nerd"],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='npc'
			)],
			visitCondition=lambda: get_cat_at_position(Position(17, 8)) is not None and get_cat_at_position(Position(17, 8)).classType == 'wizard' and can_give_item(Position(0,0)),
			dialogs=[Dialog(
				lines=["Oh,","a wizard!"],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='npc',
				lambda_after=lambda: give_item(Position(0,0), itemDict['LghtngTm'])
			)],
			postVisitDialog=[Dialog(
				lines=["Use it","wisely."],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='npc'
			)]
		),
		House(
			position=Position(1, 0),
			dialogs=[Dialog(
				lines=["This place","is dangerous."],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='cat'
			)],
		),
		House(
			position=Position(7, 13),
			dialogs=[Dialog(
				lines=["Be careful","out there."],
				left_cats=[get_cat_at_position(Position(17, 8))],
				right_cats=[npc],
				currentlyTalking='cat'
			)],
		)
	]
)

level8 = Level(
	map=map8, 
	enemies=[
		generate_enemy(2, Position(14, 9), name ='jr'),
		generate_enemy(1, Position(15, 9), name='mini'),
		generate_enemy(2, Position(8, 11), name='l'),
		mew,
		generate_enemy(3, Position(10, 5), name='wago', weapon='Slngsht'),
		generate_enemy(3, Position(4, 2), 'stand', name='xl', weapon='Stick')
	],
	number=8,
	seizePosition=Position(4, 2), 
	startingPositions=[Position(16, 3), Position(15, 3)],
	houses={
		House(
			position=Position(16, 10),
			dialogs=[Dialog(
				lines=["I Should","Probably","hint"],
				left_cats=[cat],
				right_cats=[],
				currentlyTalking='cat',
			)]
		),
		House(
			position=Position(17, 10),
			dialogs=[Dialog(
				lines=["Welcome","to the","Cats Emblem","demo!"],
				left_cats=[],
				right_cats=[cat],
				currentlyTalking='cat'
			)]
		)
	}
)

def fetch_level(level_number):
	if level_number == 1:
		from Levels import level1
		return level1
	elif level_number == 2:
		from Levels import level2
		return level2
	elif level_number == 3:
		from Levels import level3
		return level3
	elif level_number == 4:
		from Levels import level4
		return level4
	elif level_number == 8:
		from Levels import level8
		return level8
	else:
		raise ValueError(f"Level {level_number} does not exist.")
